config/routes.rb
Rails.application.routes.draw do
  get 'payroll/index'

  resources :workers_profits
  resources :time_stamps
  resources :absences
  resources :sectors
  resources :taxes
  resources :roles
  resources :workers

  get 'payroll/payslip_all', to: 'payroll#payroll', as: 'payroll_payslip_all'
  get 'payroll/payslip/:id', to: 'payroll#payslip', as: 'payroll_payslip'

  get 'worker_statistics/:id', to:'workers_profits#worker_statistics', as: 'worker_statistics'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/sector.rb
class Sector < ActiveRecord::Base
  has_many :worker
  has_many :role
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]

  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.all
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to @sector, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:name)
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_for(@sector) do |f| %>
  <% if @sector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
      <% @sector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
</div>

<% end %>

app/views/sectors/edit.html.slim
h1 Editing Sector

= render 'form'

= link_to 'Show', @sector, class: "btn btn-default"
|
= link_to 'Back', sectors_path, class: "btn btn-default"

app/views/sectors/index.html.slim
p id="notice"
  = notice
  
h1 Listing Sectors

table class="table"
  thead
    tr
      th Name
      th colspan="3"

  tbody
    - @sectors.each do |sector|
      tr
        td.name = sector.name
        td
          = link_to 'Show', sector, class: "btn btn-default"
        td
          = link_to 'Edit', edit_sector_path(sector), class: "btn btn-primary"
        td
          = link_to 'Destroy', sector, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

br

= link_to 'Back', root_path, class: "btn btn-default"
= link_to 'New Sector', new_sector_path, class: "btn btn-success"

app/views/sectors/new.html.slim
h1 New Sector

= render 'form'

= link_to 'Back', sectors_path, class: "btn btn-default"

app/views/sectors/show.html.slim
p id="notice"
  = notice

p
  strong Name: 
  = @sector.name

= link_to 'Edit', edit_sector_path(@sector), class: "btn btn-default" 
|
= link_to 'Back', sectors_path, class: "btn btn-default"