config/routes.rb
Rails.application.routes.draw do
  get 'payroll/index'

  resources :workers_profits
  resources :time_stamps
  resources :absences
  resources :sectors
  resources :taxes
  resources :roles
  resources :workers

  get 'payroll/payslip_all', to: 'payroll#payroll', as: 'payroll_payslip_all'
  get 'payroll/payslip/:id', to: 'payroll#payslip', as: 'payroll_payslip'

  get 'worker_statistics/:id', to:'workers_profits#worker_statistics', as: 'worker_statistics'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/workers_profit.rb
class WorkersProfit < ActiveRecord::Base
  belongs_to :worker
end

app/controllers/workers_profits_controller.rb
class WorkersProfitsController < ApplicationController
  before_action :set_workers_profit, only: [:show, :edit, :update, :destroy]

  # GET /workers_profits
  # GET /workers_profits.json
  def index
    @workers_profits = WorkersProfit.all
  end

  # GET /workers_profits/1
  # GET /workers_profits/1.json
  def show
  end

  # GET /workers_profits/new
  def new
    @workers_profit = WorkersProfit.new
    @workers = Worker.all.collect {|p| [ p.name, p.id ] }
    @workers.unshift([" "," "])
  end

  # GET /workers_profits/1/edit
  def edit
    @workers = Worker.all.collect {|p| [ p.name, p.id ] }
    @workers.unshift([" "," "])
  end

  # POST /workers_profits
  # POST /workers_profits.json
  def create
    @workers_profit = WorkersProfit.new(workers_profit_params)

    respond_to do |format|
      if @workers_profit.save
        format.html { redirect_to @workers_profit, notice: 'Workers profit was successfully created.' }
        format.json { render :show, status: :created, location: @workers_profit }
      else
        format.html { render :new }
        format.json { render json: @workers_profit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers_profits/1
  # PATCH/PUT /workers_profits/1.json
  def update
    respond_to do |format|
      if @workers_profit.update(workers_profit_params)
        format.html { redirect_to @workers_profit, notice: 'Workers profit was successfully updated.' }
        format.json { render :show, status: :ok, location: @workers_profit }
      else
        format.html { render :edit }
        format.json { render json: @workers_profit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers_profits/1
  # DELETE /workers_profits/1.json
  def destroy
    @workers_profit.destroy
    respond_to do |format|
      format.html { redirect_to workers_profits_url, notice: 'Workers profit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def worker_statistics
    @worker = Worker.find(params[:id])
    @task_statistics = [['Completed', @worker.workers_profit.tasks_completed],\
    ['Incompleted', @worker.workers_profit.total_tasks - @worker.workers_profit.tasks_completed]]
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_workers_profit
      @workers_profit = WorkersProfit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workers_profit_params
      params.require(:workers_profit).permit(:value, :worker_id, :tasks_completed, :total_tasks)
    end

end

app/helpers/workers_profits_helper.rb
module WorkersProfitsHelper
end

app/views/workers_profits/_form.html.erb
<%= form_for(@workers_profit) do |f| %>
  <% if @workers_profit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workers_profit.errors.count, "error") %> prohibited this workers_profit from being saved:</h2>

      <ul>
      <% @workers_profit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :tasks_completed %><br>
    <%= f.text_field :tasks_completed, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :total_tasks %><br>
    <%= f.text_field :total_tasks, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :worker_id %><br>
    <%= f.select :worker_id, @workers, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
</div>
<% end %>

app/views/workers_profits/edit.html.slim
h1 Editing Worker's Profit

= render 'form'

= link_to 'Back', workers_profits_path, class: "btn btn-default"
|
= link_to 'Show', @workers_profit, class: "btn btn-default"

app/views/workers_profits/index.html.slim
p id="notice"
 = notice

h1 Listing Worker's Profits

table class="table"
  thead
    tr
      th Worker
      th Value
      th colspan="3"

  tbody
    - @workers_profits.each do |workers_profit|
      tr
        td 
          = workers_profit.worker.name
          br
          br = link_to (workers_profit.worker.name + '\'s Statistics'), worker_statistics_path(workers_profit.worker), class: "btn btn-primary"
        td.value = workers_profit.value
        td 
          = link_to 'Show', workers_profit, class: "btn btn-default"
        td 
          = link_to 'Edit', edit_workers_profit_path(workers_profit), class: "btn btn-primary"
        td
          = link_to 'Destroy', workers_profit, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
      tr
        td
          
	  /= pie_chart Goal.group(:name).count

br

= link_to 'Back', root_path, class: "btn btn-default"
/= link_to 'New Worker\'s Profit', new_workers_profit_path, class: "btn btn-default"

app/views/workers_profits/new.html.slim
h1 New Worker's Profit

= render 'form'

= link_to 'Back', workers_profits_path, class: "btn btn-default"

app/views/workers_profits/show.html.slim
p id="notice"
  = notice

p
  strong Value:
  = @workers_profit.value

p
  strong Task Completed:
  = @workers_profit.tasks_completed

p
  strong Total Tasks:
  = @workers_profit.total_tasks

= link_to 'Back', workers_profits_path, class: "btn btn-default"
|
= link_to 'Edit', edit_workers_profit_path(@workers_profit), class: "btn btn-primary"

app/views/workers_profits/worker_statistics.html.slim
h1 Worker Statistics
p 
  strong Name: 
  = @worker.name

p 
  strong Role: 
  = @worker.role.name

p 
  strong Contracted at: 
  = @worker.admission_date
p 
  strong Tasks Completed: 
  = @worker.workers_profit.tasks_completed

p 
  strong Total Tasks: 
  = @worker.workers_profit.total_tasks

div id="chart_div" class="center-block"

= content_tag :div, class: "temp_information", data: {temp: @task_statistics} do

javascript:
  google.charts.load('current', {'packages':['corechart']});
 $( document ).ready(function() {
      // Load the Visualization API and the corechart package.
      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawPieChart);
      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      var rows = $('.temp_information').data('temp');
      function drawPieChart() {
        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows(rows);
        // Set chart options
        var options = {'title':'Tasks analytics',
                       'width':600,
                       'height':400,
                       'backgroundColor': 'transparent'
                      };
        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
 });