config/routes.rb
Rails.application.routes.draw do
  get 'payroll/index'

  resources :workers_profits
  resources :time_stamps
  resources :absences
  resources :sectors
  resources :taxes
  resources :roles
  resources :workers

  get 'payroll/payslip_all', to: 'payroll#payroll', as: 'payroll_payslip_all'
  get 'payroll/payslip/:id', to: 'payroll#payslip', as: 'payroll_payslip'

  get 'worker_statistics/:id', to:'workers_profits#worker_statistics', as: 'worker_statistics'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :role
  belongs_to :sector

  has_one :workers_profit
  has_many :absence
  has_many :time_stamp

  validates :name, :registry, :presence => true
  validates :cpf, length: { is: 11 }
  validates :registry, length: { is: 9 }
  validates :name, format: { with: /\A[a-zA-Z]+\z/,
            message: "only allows letters" }
  # add any other characters you'd like to disallow inside the [ brackets ]
  # metacharacters [, \, ^, $, ., |, ?, *, +, (, and ) need to be escaped with a \

end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
    @roles = Role.all.collect {|p| [ p.name, p.id ] }
    @roles.unshift([" "," "])
  end

  # GET /workers/1/edit
  def edit
    @roles = Role.all.collect {|p| [ p.name, p.id ] }
    @roles.unshift([" "," "])
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name, :cpf, :registry, :role_id, :admission_date)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.slim
= form_for(@worker) do |f|
  - if @worker.errors.any?
    div id="error_explanation"
      h2 = pluralize(@worker.errors.count, "error") 
        p prohibited this worker from being saved

      ul
      - @worker.errors.full_messages.each do |message|
        li = message
      
  div class="form-group"
    div class="field"
      = f.label :name
      br = f.text_field :name, class: "form-control"
    
    div class="field"
      = f.label :cpf
      br = f.text_field :cpf, class: "form-control"
    
    div class="field"
      = f.label :registry
      br = f.text_field :registry, class: "form-control"
    
    div class="field"
      = f.label :role_id
      br = f.select :role_id, @roles, class: "form-control dropdown"

    div class="field"
      = f.label :admission_date
      br = f.text_field :admission_date, class: "form-control date"

    div class="actions"
      = f.submit class: "btn btn-success"

javascript:
  $(document).ready(function(){
    $('.date').mask('00/00/0000');
    $('.cpf').mask('000.000.000-00', {reverse: true});
  });

app/views/workers/edit.html.slim
h1 Editing Worker

= render 'form'

= link_to 'Show', @worker, class: "btn btn-default" 
|
= link_to 'Back', workers_path, class: "btn btn-default"

app/views/workers/index.html.slim
p id="notice"
  = notice

h1 Listing Workers


= link_to 'Sectors', sectors_path, class: "btn btn-default pull-left"
= link_to 'Roles', roles_path, class: "btn btn-default pull-left"

table class="table"
  thead
    tr
      th Name
      th CPF
      th Registry
      th Role
      th Contracted at
      th colspan="3"


  tbody
    - @workers.each do |worker|
      tr
        td.name = worker.name
        td.cpf = worker.cpf
        td.registry = worker.registry
        td.role = worker.role.name
        td.contracted_at = worker.admission_date
        td 
          = link_to 'Show', worker, class: "btn btn-default"
        td 
          = link_to 'Edit', edit_worker_path(worker), class: "btn btn-primary"
        td 
          = link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

br

= link_to 'Back', root_path, class: "btn btn-default"
= link_to 'New Worker', new_worker_path, class: "btn btn-success"

app/views/workers/new.html.slim
h1 New Worker

= render 'form'

= link_to 'Back', workers_path, class: "btn btn-default"

app/views/workers/show.html.slim
p id="notice" class="alert"
  = notice

p
  strong Name: 
  = @worker.name

p
  strong CPF: 
  = @worker.cpf

p
  strong Registry: 
  = @worker.registry
  
p
  strong Role: 
  = @worker.role_id

p
  strong Contracted at: 
  = @worker.admission_date

= link_to 'Edit', edit_worker_path(@worker), class: "btn btn-primary" 
|
= link_to 'Back', workers_path, class: "btn btn-default"