config/routes.rb
Rails.application.routes.draw do
  get 'payroll/index'

  resources :workers_profits
  resources :time_stamps
  resources :absences
  resources :sectors
  resources :taxes
  resources :roles
  resources :workers

  get 'payroll/payslip_all', to: 'payroll#payroll', as: 'payroll_payslip_all'
  get 'payroll/payslip/:id', to: 'payroll#payslip', as: 'payroll_payslip'

  get 'worker_statistics/:id', to:'workers_profits#worker_statistics', as: 'worker_statistics'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/time_stamp.rb
class TimeStamp < ActiveRecord::Base
  belongs_to :worker
end

app/controllers/time_stamps_controller.rb
class TimeStampsController < ApplicationController
  before_action :set_time_stamp, only: [:show, :edit, :update, :destroy]

  # GET /time_stamps
  # GET /time_stamps.json
  def index
    @time_stamps = TimeStamp.all
  end

  # GET /time_stamps/1
  # GET /time_stamps/1.json
  def show
  end

  # GET /time_stamps/new
  def new
    @time_stamp = TimeStamp.new
  end

  # GET /time_stamps/1/edit
  def edit
  end

  # POST /time_stamps
  # POST /time_stamps.json
  def create
    @time_stamp = TimeStamp.new(time_stamp_params)

    respond_to do |format|
      if @time_stamp.save
        format.html { redirect_to @time_stamp, notice: 'Time stamp was successfully created.' }
        format.json { render :show, status: :created, location: @time_stamp }
      else
        format.html { render :new }
        format.json { render json: @time_stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_stamps/1
  # PATCH/PUT /time_stamps/1.json
  def update
    respond_to do |format|
      if @time_stamp.update(time_stamp_params)
        format.html { redirect_to @time_stamp, notice: 'Time stamp was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_stamp }
      else
        format.html { render :edit }
        format.json { render json: @time_stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_stamps/1
  # DELETE /time_stamps/1.json
  def destroy
    @time_stamp.destroy
    respond_to do |format|
      format.html { redirect_to time_stamps_url, notice: 'Time stamp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_stamp
      @time_stamp = TimeStamp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_stamp_params
      params.require(:time_stamp).permit(:in_hour, :out_hour, :worker_id)
    end
end

app/helpers/time_stamps_helper.rb
module TimeStampsHelper
end

app/views/time_stamps/_form.html.erb
<%= form_for(@time_stamp) do |f| %>
  <% if @time_stamp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_stamp.errors.count, "error") %> prohibited this time_stamp from being saved:</h2>

      <ul>
      <% @time_stamp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field">
    <%= f.label :in_hour %><br>
    <%= f.time_select :in_hour, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :out_hour %><br>
    <%= f.time_select :out_hour, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
</div>

<% end %>

app/views/time_stamps/edit.html.slim
h1 Editing Time Stamp

= render 'form'

= link_to 'Show', @time_stamp, class: "btn btn-default" 
|
= link_to 'Back', time_stamps_path, class: "btn btn-default"

app/views/time_stamps/index.html.slim
p id="notice"
  = notice

h1 Listing Time Stamps

table class="table"
  thead
    tr
      th In hour
      th Out hour
      th colspan="3"

  tbody
    - @time_stamps.each do |time_stamp|
      tr
        td.in_hour = time_stamp.in_hour
        td.out_hour = time_stamp.out_hour
        td 
          = link_to 'Show', time_stamp, class: "btn btn-default"
        td
          = link_to 'Edit', edit_time_stamp_path(time_stamp), class: "btn btn-primary"
        td
          = link_to 'Destroy', time_stamp, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

br

= link_to 'New Time stamp', new_time_stamp_path, class: "btn btn-success"

app/views/time_stamps/new.html.slim
h1 New Time Stamp

= render 'form'

= link_to 'Back', time_stamps_path, class: "btn btn-default"

app/views/time_stamps/show.html.slim
p id="notice"
  = notice

p
  strong In hour: 
  = @time_stamp.in_hour

p
  strong Out hour: 
  = @time_stamp.out_hour

= link_to 'Edit', edit_time_stamp_path(@time_stamp), class: "btn btn-primary"
|
= link_to 'Back', time_stamps_path, class: "btn btn-default"